import { createSlice } from '@reduxjs/toolkit';
import { act } from 'react-dom/test-utils';

const initialState = [];

// const initialState ={
//     orderItems: [orderItem]
// };
  
export const cartSlice = createSlice({
    name: 'cart',
    initialState,
    // The `reducers` field lets us define reducers and generate associated actions
    reducers: {
    
    addItem:(state, action) =>{
        //state = [...state, action.payload]; // da dodaje na state, da ga ne pregazi vec da pravi novi 
        state +=1
    },
      
    //   incrementByAmount: (state, action) => {
    //     state.qu += action.payload;
    //   },
      editItem: (state, action) =>{

      }
    },
    // The `extraReducers` field lets the slice handle actions defined elsewhere,
    // including actions generated by createAsyncThunk or in other slices.
   
  });
  export const { addItem, editItem } = cartSlice.actions;
  // more code...
  export default cartSlice.reducer;